### PR TITLE
implement snapping line start and end positions to nearby lines

### PR DESCRIPTION
**Pull request by DanielOaks**
This snaps the starting position of newly-created lines to nearby lines, unless the `alt` key is pressed.

This just manually calculates the distance for each separate line in the `lineStore`. Not sure if it'll get a bit slow for large tracks, but it seems to perform alright for now.

The zoom level hackery is a bit dodgy. Basically, I'd like it to be the same physical distance regardless of the zoom level, this almost works but seems to get a bit smaller than desired when zooming in.  I don't code much JS, so feel free to point out or fix up stuff!

### CODE REVIEW

**Comment by DanielOaks** [comment]
The way I'm doing distance calculation (with `maxSnap`) is silly. I'm gonna make a change or two and try to get it snapping the end point as well.

**Comment by DanielOaks** [comment]
Alright, that implements the end-of-line snapping and makes it a little simpler. The `ignoreLine` conditional is long, but it needs to check those points to make sure it's not trying to snap to the current line we're drawing (which causes weirdness when snapping to the end of lines).

**Comment by conundrumer** [comment]
Wow, I never had someone submit a pull request to my projects!

re. JS: if you haven't noticed around, the code is in es6, the next version of js. The tricky parts of JS are when you use objects and functions in nontrivial ways (eg prototype/class inheritance, 'this', functions as values), but that's not necessary for implementing line snapping.

re. performance: it's not unusual to have tracks that have thousands of lines. Fortunately, there's already [a method for getting nearby lines](https://github.com/conundrumer/lr/blob/master/core/tracks/Track.js#L197) in `state.trackData.track`. If I documented my code, maybe you would have found this method. I'll work on documenting the code after I get a preview build shipped next week.

In the original Line Rider, there's a weird physics feature where snapped lines have their endpoints invisibly extended, to prevent Bosh's (the rider) contact points from literally falling through the cracks. This was the source of some bugs, and this also involves modifying the lines that get snapped to, which is more complicated to manage. Fortunately, it's not essential, so that can be handled another time.

I'll take over from here.

**Comment by DanielOaks** [comment]
Awesome, I'll keep that in mind!

I'm pretty new to using JS for anything than tiny little frontend things
and userscripts, (unfamiliar with objects and such), but I'll definitely
look into ES6 stuff. I'll keep an eye on what you do from here, thanks!

**Comment by conundrumer** [comment]
7da7b1fdb0b7fddbaa2e11176a774455857e2e31

Are you familiar with functional programming? I did some of that over here.

**Comment by DanielOaks** [comment]
I'm more familiar with OO than with functional (Python's my main language), just unfamiliar with the semantics of JS. I'll keep having a look and playing around with it though, that's a really interesting commit.

**Pull request merged**
